<?php

namespace App\Filament\Resources\Voters\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class VoterInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('house_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('serial_no')
                    ->placeholder('-'),
                TextEntry::make('part_no')
                    ->placeholder('-'),
                TextEntry::make('epic_no')
                    ->placeholder('-'),
                TextEntry::make('name'),
                TextEntry::make('father_husband_name')
                    ->placeholder('-'),
                TextEntry::make('gender')
                    ->placeholder('-'),
                TextEntry::make('age')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('dob')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('mobile')
                    ->placeholder('-'),
                TextEntry::make('whatsapp')
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label('Email address')
                    ->placeholder('-'),
                TextEntry::make('house_no')
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('photo')
                    ->placeholder('-'),
                TextEntry::make('caste')
                    ->placeholder('-'),
                TextEntry::make('religion')
                    ->placeholder('-'),
                TextEntry::make('category')
                    ->placeholder('-'),
                TextEntry::make('occupation')
                    ->placeholder('-'),
                TextEntry::make('education')
                    ->placeholder('-'),
                TextEntry::make('support_level'),
                TextEntry::make('party_support')
                    ->placeholder('-'),
                TextEntry::make('party_preference')
                    ->placeholder('-'),
                IconEntry::make('is_influencer')
                    ->boolean(),
                IconEntry::make('is_volunteer')
                    ->boolean(),
                TextEntry::make('last_contact_date')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('voter_type')
                    ->placeholder('-'),
                TextEntry::make('blood_group')
                    ->placeholder('-'),
                IconEntry::make('disability')
                    ->boolean(),
                IconEntry::make('government_scheme')
                    ->boolean(),
                TextEntry::make('government_scheme_name')
                    ->placeholder('-'),
                TextEntry::make('facebook')
                    ->placeholder('-'),
                TextEntry::make('instagram')
                    ->placeholder('-'),
                TextEntry::make('twitter')
                    ->placeholder('-'),
                TextEntry::make('family_members')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('booth_committee_role')
                    ->placeholder('-'),
                TextEntry::make('panna_pramukh')
                    ->placeholder('-'),
                TextEntry::make('polling_agent')
                    ->placeholder('-'),
                TextEntry::make('priority'),
                TextEntry::make('next_followup')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('latitude')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('longitude')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('internal_notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('remarks')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('is_active')
                    ->boolean(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
