<x-filament-panels::page>
    @php($stats=$this->stats) @php($issues=$this->issues)
    <style>
        .it-wrap{display:flex;flex-direction:column;gap:18px}.it-hero,.it-panel{border:1px solid rgba(124,58,237,.16);border-radius:20px;background:#fff;box-shadow:0 18px 48px -34px rgba(76,29,149,.48);overflow:hidden}.it-hero{padding:24px;background:linear-gradient(125deg,#fff,#f5f3ff 62%,#ede9fe)}.it-head{display:flex;justify-content:space-between;gap:16px}.it-title{font-size:27px;font-weight:900;color:#111827}.it-sub{margin-top:6px;color:#6b7280;font-size:13px}.it-add{padding:11px 16px;border-radius:12px;background:linear-gradient(135deg,#7c3aed,#17111f);color:#fff;font-size:12px;font-weight:850;text-decoration:none}.it-filters{display:grid;grid-template-columns:2fr 1.3fr 1.3fr auto;gap:12px;margin-top:20px;align-items:end}.it-field label{display:block;margin-bottom:6px;font-size:10px;font-weight:900;color:#6b7280;text-transform:uppercase}.it-select{width:100%;min-height:44px;border:1px solid rgba(124,58,237,.2);border-radius:12px;padding:9px;background:#fff}.it-reset{height:44px;border:0;border-radius:12px;color:#5b21b6;background:#ede9fe;font-weight:800}.it-stats{display:grid;grid-template-columns:repeat(6,1fr);gap:11px}.it-stat{padding:17px;border:1px solid rgba(124,58,237,.14);border-radius:16px;background:#fff}.it-stat span{font-size:10px;font-weight:900;color:#7c3aed;text-transform:uppercase}.it-stat strong{display:block;margin-top:7px;font-size:24px;color:#111827}.it-list a{display:grid;grid-template-columns:1fr auto;gap:12px;padding:16px 19px;border-bottom:1px solid #eef0f3;text-decoration:none}.it-name{font-size:13px;font-weight:900;color:#111827}.it-meta{margin-top:7px;color:#6b7280;font-size:10px}.it-badge{display:inline-block;margin-left:7px;padding:4px 7px;border-radius:99px;background:#ede9fe;color:#5b21b6;font-weight:850}.it-due{font-size:10px;color:#6b7280}.it-due.bad{color:#dc2626;font-weight:850}.it-empty{padding:50px;text-align:center;color:#9ca3af}html.dark .it-hero,html.dark .it-panel{border-color:rgba(167,139,250,.25);background:linear-gradient(145deg,#09080e,#151020)}html.dark .it-hero{background:linear-gradient(125deg,#09080e,#171023 62%,#27113e)}html.dark .it-title,html.dark .it-stat strong,html.dark .it-name{color:#f8fafc}html.dark .it-sub,html.dark .it-field label,html.dark .it-meta{color:#aaa4b8}html.dark .it-select{color:#f8fafc;background:#100d17;color-scheme:dark}html.dark .it-stat{border-color:rgba(167,139,250,.2);background:#100d17}html.dark .it-list a{border-color:rgba(148,163,184,.13)}@media(max-width:1000px){.it-stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.it-filters{grid-template-columns:1fr 1fr}.it-stats{grid-template-columns:1fr 1fr}.it-head{flex-direction:column}}
    </style>
    <div class="it-wrap"><section class="it-hero"><div class="it-head"><div><div class="it-title">📣 Public Issue Command</div><div class="it-sub">Register, assign, escalate and close public issues with an auditable SLA timeline.</div></div>@if(auth()->user()?->can('campaign_issue.create'))<a class="it-add" href="{{ $this->createIssueUrl() }}">＋ Register Issue</a>@endif</div><div class="it-filters"><div class="it-field"><label>Assembly</label><select class="it-select" wire:model.live="constituencyId"><option value="">All Assemblies</option>@foreach($this->constituencies as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select></div><div class="it-field"><label>Status</label><select class="it-select" wire:model.live="status"><option value="">All Statuses</option>@foreach(\App\Models\CampaignIssue::STATUSES as $v=>$l)<option value="{{$v}}">{{$l}}</option>@endforeach</select></div><div class="it-field"><label>Category</label><select class="it-select" wire:model.live="category"><option value="">All Categories</option>@foreach(\App\Models\CampaignIssue::CATEGORIES as $v=>$l)<option value="{{$v}}">{{$l}}</option>@endforeach</select></div><button class="it-reset" wire:click="resetFilters">Reset</button></div></section>
        <div class="it-stats">@foreach(['total'=>'Total','open'=>'Active','escalated'=>'Escalated','resolved'=>'Awaiting Closure','closed'=>'Closed','overdue'=>'Overdue'] as $key=>$label)<div class="it-stat"><span>{{$label}}</span><strong>{{number_format($stats[$key])}}</strong></div>@endforeach</div>
        <section class="it-panel"><div class="it-list">@forelse($issues as $issue)<a href="{{$this->issueUrl($issue)}}"><div><div class="it-name">{{$issue->title}} <span class="it-badge">{{$issue->status}}</span></div><div class="it-meta">{{$issue->issue_code}} · {{$issue->category}} · {{$issue->constituency?->name}} @if($issue->village)· {{$issue->village->name}}@endif · Responsible: {{$issue->assignee?->name ?? 'Unassigned'}}</div></div><div class="it-due {{$issue->is_overdue?'bad':''}}">{{$issue->due_at?($issue->is_overdue?'Overdue · ':'Due · ').$issue->due_at->format('d M, h:i A'):'No SLA'}}</div></a>@empty<div class="it-empty">No issues found. Register the first public issue.</div>@endforelse</div></section>
    </div>
</x-filament-panels::page>
